//  1. Function vs Method
// A. Function
const startGameBtn = document.getElementById('start-game-btn');


function startGame(){
    console.log("game is starting.....")
}


// startGame();  // call function default   Direct execution  
console.log("startGameBtn",startGameBtn)
startGameBtn.addEventListener('click',startGame)   // Call function on click.


//1."document" is lobal available variable in javascript.
//2."addEventListener" is method which is present in "startGameBtn" object generated by
//  "document.getElementById('start-game-btn')" method which is exist is document.


//B. Method: 
// const person = {
//     name: 'max',
//     greet: function greet(){
//         console.log("Hello there...");
//     }
// }

// person.greet();  // calling a function in side a object is method

//  Functions are Object
console.log(typeof startGame())

console.log(typeof startGame)

console.dir(startGame)
